var squares = ['We\'re taking it to the next level',
                'Siri kicks off the keynote',
                'iOS 8',
                'Jonny Ive describes something as magical',
                'Jonny Ive is actually on stage',
                'One more thing...',
                'Apple TV SDK',
                'iWatch',
                'Awkward presentation from non-Apple exec',
                'iPad User Accounts',
                '4.7" iPhone',
                '5.5" iPhone',
                'Siri SDK',
                'Revolutionary',
                'Beats Demo',
                'Hairforce one',
                'Video of Apple products changing people\'s lives',
                'Live demo of some hardware fails',
                'Eddy Cue\'s shirt is not camera friendly',
                'Android mentioned',
                'Infinity Blade',
                'Eddy Cue\'s shirt not tucked in',
                '64-Bit only Mac App Store',
                'Smart Home',
                'It\'s our best X yet',
                'Only Apple could do this',
                '...and we\'d love to show it to you now',
                'Angela Ahrendts on stage',
                'Chamfered',
                'Solid piece of aluminium',
                'We\'ve shot a video of the store opening and we\'d love to show it to you now',
                'The best 8MP camera',
                '...and it\'s available today',
                'TestFlight',
                'Video of the Spaceship Campus',
                'Video of the manufacturing process',
                'LiquidMetal',
                'Sapphire',
                'It\'s that easy',
                'It just works',
                'Phil Schiller reads off a list of specifications',
                'iOS adoption chart',
                'NFC',
                'U2',
                'micropayments',
                'non-watch wearables',
                'wearable micropants',
                'Super retina (@3x)',];