var squares = ['We\'re taking it to the next level',
                'Siri kicks off the keynote',
                'iOS 9 (Monarch)',
                'Jonny Ive describes something as magical',
                'Jonny Ive is actually on stage',
                'One more thing...',
                'Apple TV SDK',
                'WatchKit 2.0',
                'Swift 2.0',
                'Remote View Controllers',
                'Xcode 7.0',
                'Awkward presentation from non-Apple exec',
                'iPad User Accounts',
                'Mac OS X Gala (10.11)',
                'Siri SDK',
                'Revolutionary',
                'Beats streaming demo',
                'Hairforce one',
                'Video of Apple products changing people\'s lives',
                'Live demo of some hardware fails',
                'Eddy Cue\'s shirt is not camera friendly',
                'Android mentioned',
                'Infinity Blade',
                'Eddy Cue\'s shirt not tucked in',
                '64-Bit only Mac App Store',
                'Mac OS X follows iOS UI styling',
                'It\'s our best X yet',
                'Only Apple could do this',
                'Jimmy Iovine on stage',
                'Moscone West is the biggest venue we could find',
                '...and we\'d love to show it to you now',
                'Angela Ahrendts on stage',
                'Chamfered',
                'Solid piece of aluminium',
                'We\'ve shot a video of the store opening and we\'d love to show it to you now',
                '...and it\'s available today',
                'TestFlight',
                'Video of the Spaceship Campus',
                'Video of the manufacturing process',
                'Dre on stage',
                'OS X running on Arm64',
                'It\'s that easy',
                'It just works',
                'Phil Schiller reads off a list of specifications',
                'iOS adoption chart',
                'Retina Cinema Display',
                'UXKit',
                'Painfully unfunny "comedy" segment',
                'Isn\'t it just gorgeous?',
                'iPad Pro',
                'San Francisco font across iOS and OS X',
                'Apple Watch Sales Update',
                'Apple Exec \'Amazed\' at customer response to product',
                'Tim Cook opens with "So, the Christy Turlington Burns blog. What was that about?"',
                'Side by side iPad',
                'Home automation',
                'Finely tuned',
		'China highlighted',
		'ResearchKit',
		'Force Touch on iOS',
		'Kevin Lynch on stage',
		'A woman on stage who is not Angela Ahrendts'];
